### PR TITLE
Refactor

### PR DESCRIPTION
**Pull request by loverajoel**
#### What does this PR do?

Delete unnecessary files and add first iteration for the search
#### Any background context you want to provide?

Please review deleted files, maybe I deleted some files wrong

### CODE REVIEW

**Comment by Cosmitar** [comment]
I think that initialState is good to have a store tree at a glance. helps to understand the app structure. For example

``` javascript
{
  searchSection: {
    searchText: '', 
    isSearching: false
  }, 
  resultsSection: {
    resultsList: []
  }
}
```

Don't you think?

**Comment by Cosmitar** [comment]
Hard to markup on mobile :p

**Comment by loverajoel** [comment]
Yep, we can do it in the future.

**Comment by loverajoel** [comment]
I need to merge this PR, so...

**Pull request merged**
