### PR TITLE
Add GA events

### PR DESCRIPTION
**Pull request by loverajoel**
Just add a couple of events

### CODE REVIEW

**Comment by loverajoel** [comment]
another's events to track?

**Comment by Cosmitar** [comment]
What about some insights? like _most played video_ or _most skipped video_.
When a video starts can be tracked on file:_PlayerManager.js_ line:**175**
could be something like `ga('send', 'event', 'video', 'play', `{this._player.getVideoData().video_id}-{this._player.getVideoData().title}`);` (improve this code)

When a video is skipped can be tracked on file:_PlayerManager.js_ line:**228**
could be something like `ga('send', 'event', 'video', 'skip', `{this._player.getVideoData().video_id}-{this._player.getVideoData().title}`);` (improve this code).

thoughts?

**Comment by Cosmitar** [comment]
I added my suggestions about tracking play and skip events.
:shipit:

**Comment by loverajoel** [comment]
awesome

**Pull request merged**
